In [1]:
list1 = [1, 2, 3]
print(type(list1))
print(list1[0], list1[-1]) #인덱스가 음수일 경우 리스트의 끝에서부터 셈

<class 'list'>
1 3


In [2]:
list1[1] = "str1"
print(list1) #리스트는 자료형이 다른 요소도 저장 가능

[1, 'str1', 3]


In [13]:
list2 = range(10)
print(list2)
print(type(list2)) #range Type출력

range(0, 10)
<class 'range'>


In [14]:
list2 = list(list2) #List Type으로 변환
print(type(list2))
print(list2)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
print(list2[2:4]) # 인덱스 2에서 4(제외)까지 슬라이싱
print(list2[2:]) # 인덱스 2에서 끝까지 슬라이싱
print(list2[:2]) # 처음부터 인덱스 2(제외)까지 슬라이싱
print(list2[:]) # 전체 리스트 슬라이싱
print(list2[::2]) # 2씩 증가하면서 리스트 출력
print(list2[:-1]) # 슬라이싱 인덱스는 음수도 가능

[2, 3]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
list2[2:4] = [8, 9] # 슬라이스된 리스트에 새로운 리스트 할당
list2[2:5] = [8, 9] # ??
print(list2)

[0, 1, 8, 9, 5, 6, 7, 8, 9]


In [19]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 3)
    print(squares)
print(squares)



cat
dog
monkey
[0]
[0, 1]
[0, 1, 8]
[0, 1, 8, 27]
[0, 1, 8, 27, 64]
[0, 1, 8, 27, 64]


In [20]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# 출력 "negative", "zero", "positive", 한 줄에 하나씩 출력.



negative
zero
positive


In [ ]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s!' % name.upper())
    else:
        print ('Hello, %s' % name)

hello('Bob') # 출력 "Hello, Bob"
hello('Fred', loud=True)  # 출력 "HELLO, FRED!"



Hello, Bob
HELLO, FRED!


In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)
for x, y, _ in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]): #???
    print(x, y, z)



1 4 7
2 5 8
3 6 9
1 4 9
2 5 9
3 6 9


In [ ]:
# Packing
print(1)  # print함수는 몇개의 인자를 받든지 상관하지 않음
print("a")
print("aa", "bb")

######################
def func(*args):
    print(args)
    print(type(args))  # Tuple


func(1, 2, 3, 'a')

######################

def func2(**kwargs):
    print(kwargs)
    print(type(kwargs))  # Dictionary


func2(a=1, b=2, c=3, d='a')



1
a
aa bb
(1, 2, 3, 'a')
<class 'tuple'>
{'a': 1, 'b': 2, 'c': 3, 'd': 'a'}
<class 'dict'>


In [ ]:
# Unpacking

def printSum(a, b, c):
    total = a + b + c
    print(total)
    return


lst = [1, 2, 3]

# printSum(lst) #Error
printSum(*lst)


def print_customer_info(**kwargs):
    print(kwargs)


print_customer_info(name='lee', age='30')  # {'name': 'lee', 'age': '30'}
print_customer_info(name='lee', age='30', address='seoul')  # {'name': 'lee', 'age': '30', 'address': 'seoul'}
# print_customer_info('lee', '30') #Error



6
{'name': 'lee', 'age': '30'}
{'name': 'lee', 'age': '30', 'address': 'seoul'}


In [24]:
class HelloWorld():
    def __init__(self):
        pass


h1 = HelloWorld()
h2 = HelloWorld()


# helloworld() #Error


class HelloWorld():
    def __init__(self):
        print("Hi")

    def __call__(self):
        print("Hello world")


h = HelloWorld()

# helloworld()  # Hello world
h()


Hi
Hello world


In [ ]:
class Module():
    def __init__(self):
        #Initialize
        None
    def __call__(self, *input, **kwargs):
        ...
        result = self.forward(*input, **kwargs)



In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        return x

n = Net()
print(n)

# n(inputData) inputData -> x -> foward(x)



Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
)


In [27]:
import numpy as np

a = np.array([1, 2, 3])  # rank가 1인 배열 생성
print(type(a))            # 출력 "<type 'numpy.ndarray'>"
print(a.shape)            # 출력 "(3,)"
print(a.ndim)               # 출력 "1"
print(a[0], a[1], a[2])   # 출력 "1 2 3"
a[0] = 5                 # 요소를 변경
print(a)                  # 출력 "[5, 2, 3]"

b = np.array([[1,2,3],
              [4,5,6]])   # rank가 2인 배열 생성
print(b.shape)                     # 출력 "(2, 3)"
print(b.ndim)                     # 출력 "2"
print(b[0])
print(b[0, 0], b[0, 1], b[1, 0])   # 출력 "1 2 4"



<class 'numpy.ndarray'>
(3,)
1
1 2 3
[5 2 3]
(2, 3)
2
[1 2 3]
1 2 4


In [28]:
import numpy as np

a = np.zeros((2,2))  # 모든 값이 0인 배열 생성
print(a)              # 출력 "[[ 0.  0.]
                     #       [ 0.  0.]]"

b = np.ones((1,2))   # 모든 값이 1인 배열 생성
print(b)              # 출력 "[[ 1.  1.]]"

c = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성
print(c)               # 출력 "[[ 7.  7.]
                      #       [ 7.  7.]]"

d = np.eye(4)        # 2x2 단위행렬 생성
print(d)              # 출력 "[[ 1.  0.]
                     #       [ 0.  1.]]"

e = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(e)                     # 임의의 값 출력 "[[ 0.91940167  0.08143941]
                            #                  [ 0.68744134  0.87236687]]"



[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.68295074 0.47605452]
 [0.40358222 0.94368967]]


In [32]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]
             )
a[1, 2]

a = np.array([[[1,2],
               [3,4],
               [5,6]],
               
               [[7,8],
               [9,10],
               [11,12]]])
a.shape
a[1, 1, 1]

10

In [34]:
import numpy as np

# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열 생성;
# b는 shape가 (2,2)인 배열이 됨:
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됨.
print(a[0, 1])   # 출력 "2"
b[0, 0] = 77    # b[0, 0]은 a[0, 1]과 같은 데이터
print(a[0, 1])   # 출력 "77"



[[2 3]
 [6 7]]
2
77


In [36]:
import numpy as np

# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


b = np.reshape(a, (2, 6))
#b = a.reshape(2, 6) # Equivalent Function
print(b)

b = np.reshape(a, (-1, 3))
print(b)
# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됨.
print(b[0, 0])   # 출력 "2"
b[0, 0] = 77    # b[0, 0]은 a[0, 0]과 같은 데이터
print(a[0, 0])   # 출력 "77"



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1
77
