In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [24]:
x_train = torch.FloatTensor([[1], 
                             [2], 
                             [3]])
y_train = torch.FloatTensor([[2], 
                             [3], 
                             [4]])
# y = W * x + b
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [25]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000

In [29]:
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)  # Error, Cost, Loss Function

    # cost로 H(x) 개선
    optimizer.zero_grad()  # 1 : gradient 초기화

    cost.backward()  # 2 : gradient 계산

    if epoch % 100 == 0:
        print("W:", W, "W의 Gradient:", W.grad) 
        print("b:", b, "b의 Gradient:", b.grad)
    
    optimizer.step()  # 3 : gradient 빼서 update
    
    if epoch % 100 == 0:
        print("W:", W, "W의 Gradient:", W.grad) 
        print("b:", b, "b의 Gradient:", b.grad)
   
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f}, Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

W: tensor([1.0186], requires_grad=True) W의 Gradient: tensor([0.0045])
b: tensor([0.9578], requires_grad=True) b의 Gradient: tensor([-0.0101])
W: tensor([1.0185], requires_grad=True) W의 Gradient: tensor([0.0045])
b: tensor([0.9579], requires_grad=True) b의 Gradient: tensor([-0.0101])
Epoch    0/1000 W: 1.019, b: 0.958, Cost: 0.000255
W: tensor([1.0146], requires_grad=True) W의 Gradient: tensor([0.0035])
b: tensor([0.9668], requires_grad=True) b의 Gradient: tensor([-0.0080])
W: tensor([1.0146], requires_grad=True) W의 Gradient: tensor([0.0035])
b: tensor([0.9669], requires_grad=True) b의 Gradient: tensor([-0.0080])
Epoch  100/1000 W: 1.015, b: 0.967, Cost: 0.000158
W: tensor([1.0115], requires_grad=True) W의 Gradient: tensor([0.0028])
b: tensor([0.9739], requires_grad=True) b의 Gradient: tensor([-0.0063])
W: tensor([1.0114], requires_grad=True) W의 Gradient: tensor([0.0028])
b: tensor([0.9740], requires_grad=True) b의 Gradient: tensor([-0.0063])
Epoch  200/1000 W: 1.011, b: 0.974, Cost: 0.000097
W

In [27]:
print(W)
print(b)

tensor([1.0186], requires_grad=True)
tensor([0.9578], requires_grad=True)


In [28]:
5 * W + b

tensor([6.0506], grad_fn=<AddBackward0>)