In [ ]:
# Problem 1

import numpy as np

a = np.arange(24)
a = np.reshape(a, (2, 3, 4))

print("Shape: ", a.shape)
print("Value: ", a)

Shape:  (2, 3, 4)
Value:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Problem 2

print(a[0, 1:3, 2:4])
#print(a[0, 1:3, 2:]) 도 가능

print(a[1, 1:, :3])

[[ 6  7]
 [10 11]]
[[16 17 18]
 [20 21 22]]


In [1]:
!ls

sample_data  score.csv


In [6]:
# Problem 3

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from numpy import genfromtxt


class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)


my_data = genfromtxt('score.csv', delimiter=',')
x_train = torch.FloatTensor(my_data[:, :-1])
y_train = torch.FloatTensor(my_data[:, -1:])
x_test = torch.FloatTensor([70, 80, 90])

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

torch.Size([25, 3])
torch.Size([25, 1])
torch.Size([3])


In [7]:
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 500
for epoch in range(nb_epochs + 1):    # H(x) 계산
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)  

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()  # gradient 계산
    optimizer.step()  # update

    # 20번마다 로그 출력
    if epoch % 20 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()		#list(model.parameters())[0].data[0][0]
        ))

print("Answer: ", model(x_test).data[0])


Epoch    0/500 Cost: 29605.177734
Epoch   20/500 Cost: 26.561234
Epoch   40/500 Cost: 26.296589
Epoch   60/500 Cost: 26.035717
Epoch   80/500 Cost: 25.778505
Epoch  100/500 Cost: 25.524839
Epoch  120/500 Cost: 25.274738
Epoch  140/500 Cost: 25.028139
Epoch  160/500 Cost: 24.784946
Epoch  180/500 Cost: 24.545137
Epoch  200/500 Cost: 24.308681
Epoch  220/500 Cost: 24.075493
Epoch  240/500 Cost: 23.845537
Epoch  260/500 Cost: 23.618767
Epoch  280/500 Cost: 23.395136
Epoch  300/500 Cost: 23.174599
Epoch  320/500 Cost: 22.957117
Epoch  340/500 Cost: 22.742622
Epoch  360/500 Cost: 22.531082
Epoch  380/500 Cost: 22.322449
Epoch  400/500 Cost: 22.116684
Epoch  420/500 Cost: 21.913731
Epoch  440/500 Cost: 21.713585
Epoch  460/500 Cost: 21.516167
Epoch  480/500 Cost: 21.321445
Epoch  500/500 Cost: 21.129417
Answer:  tensor(156.1170)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8326, 0.5741, 0.6190]], requires_grad=True), Parameter containing:
tensor([0.1795], requires_grad=True)]
